name:    yesod-app
version: "0.0.0"

dependencies:
- base
- relude
- aeson
- aeson-optics
- aeson-schemas
- bytestring
- case-insensitive
- classy-prelude
- classy-prelude-conduit
- classy-prelude-yesod
- conduit
- containers
- data-default
- directory
- email-validate
- safe-exceptions
- fast-logger
- fb
- file-embed
- foreign-store
- forma
- hjsmin
- http-client
- http-conduit
- jwt
- monad-control
- monad-logger
- mtl
- optics
- generic-optics
- esqueleto
- hasql
- hasql-th
- persistent
- persistent-postgresql
- persistent-template
- safe
- servant
- servant-server
- servant-flatten
- shakespeare
- template-haskell
- text
- time
- transformers
- unordered-containers
- vector
- wai
- wai-extra
- wai-logger
- warp
- yaml
- yesod
- yesod-core
- yesod-auth
- yesod-auth-fb
- yesod-fb
- yesod-form
- yesod-persistent
- yesod-static
- yesod-test
- hspec >=2.0.0

default-extensions:
- BangPatterns
- BlockArguments
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- EmptyCase
- EmptyDataDecls
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- PartialTypeSignatures
- PatternSynonyms
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- ViewPatterns

ghc-options:
- -fwrite-ide-info
- -hiedir=.hie/

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2

# Runnable executable for our application
executables:
  yesod-app:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yesod-app
    when:
    - condition: flag(library-only)
      buildable: false

# Test suite
tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - yesod-app

# Define flags used by "yesod devel" to make compilation faster
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
